[package]
name = "evergreen"
version = "0.1.0"
authors = ["Bill Erickson <berickxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mptc = { path = "../mptc" }
opensrf = { path = "../opensrf" }
marc = { path = "../marc" }
roxmltree = "0.18"
chrono = "0.4"
chrono-tz = "0.8"
yaml-rust = "0.4"
log = "0.4"
json = "0.12"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
#regex = "1.7"                                                                
regex = "1.9"                                                                
getopts = "0.2"
md5 = "0.7"
rand = "0.8.5"

# Used by (at least) the parallel export script
threadpool = "1.8"

# Needed for DB / JSON data translations
pg_interval = "0.4"
rust_decimal = { version = "1.26", features = ["db-postgres"] }

# for egsh
# could be make optional
# Issues with deriving Default for enums in v10.1.0
rustyline = "10.1"
atty = "0.2"
# Bringing this in because it supports JSON stream parsing, which is
# not supported by "json".  Ideally, we would replace "json" with
# "serde_json" in opensrf, etc., but that will be a pretty big job,
# so I'm starting here.
serde_json = "1.0.96"

# For gateway
url = "2.3"

[[example]]
name = "basic-requests"

[[bin]]
# End-to-end test for open-ils.rs-store
name = "rs-store-e2e"
path = "src/bin/eg-svc-rs-store/rs-store-e2e.rs"
